version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-lab8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CCLab8
    ports:
      - "3311:3306"
    volumes:
      - lab8database:/var/lib/mysql

  lab8fastapi:
    build:
      context: .
    image: lab8fastapi:latest
    container_name: lab8fastapi
    restart: always
    ports:
      - "8080:8080"

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: miniolab8
      MINIO_ROOT_PASSWORD: 12345678
    volumes:
      - minio_data:/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postfix:
    image: boky/postfix:latest
    container_name: postfix
    restart: always
    environment:
      ALLOWED_SENDER_DOMAINS: wit.edu
      HOSTNAME: mail.local
    ports:
      - "1587:587"
    volumes:
      - postfix_data:/var/spool/postfix

volumes:
  lab8database:
  minio_data:
  redis_data:
  postfix_data:
