version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CCLab8
    ports:
      - "3307:3306"
    volumes:
      - lab8database:/var/lib/mysql

  lab8fastapi:
    build:
      context: .
    image: lab8fastapi:latest
    container_name: lab8fastapi
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - minio
      - postfix

  minio:
    image: minio/minio
    container_name: minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ozan
      MINIO_ROOT_PASSWORD: 123456
    volumes:
      - minio-data:/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postfix:
    image: boky/postfix
    container_name: postfix
    restart: always
    environment:
      - ALLOWED_SENDER_DOMAINS=example.com
      - POSTFIX_myhostname=mail.example.com
      - POSTFIX_mynetworks=127.0.0.0/8
    ports:
      - "1025:25"
    volumes:
      - postfix-spool:/var/spool/postfix
      - postfix-log:/var/log

volumes:
  lab8database:
  minio-data:
  redis_data:
  postfix-spool:
  postfix-log:
